### ISSUE TITLE
Setting-Privacy-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#10]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221158698-39f39cf1-ea28-4e52-9094-3779aa12b6cc.png)

**Comment by evergreenx** [comment]
@sheyi103 assign this to me

**Comment by sookwalinga** [comment]
@sheyi103 I see @evergreenx requested to work on this one, please assign it to him and move it to "In progress"
