### ISSUE TITLE
Setting-Support-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#12]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221159985-53ec1880-4762-493e-a7e9-0630c406b57c.png)

**Comment by evergreenx** [comment]
@sheyi103 assign this to me

**Comment by jenniekibiri** [comment]
The endpoint is ready for this task we didn't have a backend ticket for it .

**Comment by sheyi103** [comment]
it will be assigned to you @jenniekibiri
