### ISSUE TITLE
Setting-FAQ-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#13]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221164938-62a6090c-fa31-4309-a39a-ed960520f4f5.png)

**Comment by sookwalinga** [comment]
@sheyi103 please assign this to me and move it to "In progress"
