### ISSUE TITLE
SplashScreen-Admin-app- Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#2]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221146299-132e14c3-d68f-492b-8976-81913c6a134c.png)

**Comment by peculiaruc** [comment]
> @sheyi103 plus this

Start work please

**Comment by sookwalinga** [comment]
none the less I have created a splash screen as per the screenshot provided along with this issue
