### ISSUE TITLE
Profile-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#6]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221151190-6672760c-a78c-4f8b-87fa-93c2539b4508.png)

**Comment by mowfaqqa** [comment]
@sheyi103 I'd like to work on this
