### ISSUE TITLE
Setting-Screen-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#7]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221152172-fd4095b6-33d4-4567-88b1-2538263deb87.png)
![image](https://user-images.githubusercontent.com/35475543/221152448-e1230484-e152-42cb-9d19-f94f6e967dce.png)

**Comment by sookwalinga** [comment]
@sheyi103 please assign this to @Muwaff and move it to blocked, he worked on the UI, now waiting for api

**Comment by mowfaqqa** [comment]
@sheyi103 I would like to work on this
