### ISSUE TITLE
Settings-Password-Admin-App - Sprint 1

### ISSUE THREAD

**Issue by peculiaruc** [ALCOpenSource/Mentor-Management-System-Team-7#8]
Description:

- Build the Screen using the style guide.
- Integrate Screen with the Backend

![image](https://user-images.githubusercontent.com/35475543/221154730-9aba4d85-11f0-4887-941f-969d8b95e03a.png)
![image](https://user-images.githubusercontent.com/35475543/221155759-6fee2779-7e08-4b70-bc09-033974cdbf0d.png)

**Comment by sookwalinga** [comment]
@sheyi103 can I take this on, as it is still related to authentication

**Comment by mowfaqqa** [comment]
@sheyi103 and @sookwalinga I mistakenly worked on the first screen of this task so maybe I should just complete the task since I already started it

![Image](https://user-images.githubusercontent.com/71173373/232208998-6ed47d78-9c7d-4a69-a510-ee665ed0dd11.png)
